version: 3.8
services:
  myredis-server:
    build: .
    image: myredis-server
    depends_on:
      - redis
      - db
    ports:
      - 8080:8889
  redis:
    image: "redis:6.0.8"
  db:
    image: mysql:5.7
    volumes:
    - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: testdb
      MYSQL_PASSWORD: testdb
volumes:
  db_data: {}